### ISSUE TITLE
CentOS7系统下点击关于链接会死机

### ISSUE THREAD

**Issue by auslin45** [hauntek/crysadm#3]
反馈一个BUG，不知道是不是个例，我的系统是CentOS 7 64位，python3.6，最新代码，点击关于出不来页面，过一会之后电脑就黑屏无反应了，风扇转速变高，目前只用命令行来检查更新，上一个版本代码就没问题

**Comment by hauntek** [comment]
好的，晚点我检查下这个问题，请留意后续更新

**Comment by auslin45** [comment]
最新代码已经修复死机问题了，非常感谢！
