### ISSUE TITLE
登陆失败，错误信息：协议不合法，请联系客服确认！。

### ISSUE THREAD

**Issue by zktz** [hauntek/crysadm#5]
提示这个，还有
您的帐号存在异常,请登录安全中心确认！

都登录不了

**Comment by hauntek** [comment]
这个一般是迅雷服务器那边的问题，估计和你ip有关，你试试迅雷账号改成迅雷UID再试试登录

**Comment by reizhi** [comment]
same issue

**Comment by zktz** [comment]
问题解决，是IP问题。国外IP不行了，使用国内IP的服务器就好了。可以关闭了，多谢。 @hauntek

**Comment by monokoo** [comment]
使用国外IP代理，手动用官方客户端登录帐号，会出现验证码需要填写，希望能添加上自动填写验证码部分，谢谢

**Comment by hauntek** [comment]
迅雷服务器登陆接口那边，一般限制国外IP进行登陆，所以不建议使用国外IP，就算你登陆了，在请求建工数据一样不会正常返回数据

**Comment by monokoo** [comment]
好的，明白了。非常感谢回复

>
